version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: subha41/we-share-api
    container_name: we-share-api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
